runtime: python39
entrypoint: gunicorn -b :$PORT app:app
instance_class: F1
automatic_scaling:
  max_instances: 1


handlers:

- url: /static
  static_dir: static

- url: /.*
  script: auto
  secure: always